// Retrieves all of the users in the database
GET http://localhost:3000/Users


###

// Creates a new user and adds it to the database
POST http://localhost:3000/Users
Content-Type: application/json 

{
    "email":"nijika@bocchi.jp",
    "password":"nijikadabest"
}

###

// Deletes a user given the email address (after the email/"EMAIL_HERE"
DELETE http://localhost:3000/Users/email/bocchi@bocchi.jp


###

// Queries ONE person given email and password as parameter
GET http://localhost:3000/Users
Content-Type: application/json

{
    "email":"nijika@bocchi.jp",
    "password":"nijikadabest"
}


###
POST http://localhost:3000/Users/login
Content-Type: application/json

{
    "email" : "bocchi@bocchi.jp",
    "password":"literallybocchi"
}


###
GET http://localhost:3000/Users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiYm9jY2hpQGJvY2NoaS5qcCIsImlhdCI6MTcwOTg0MjMzMH0.egdaa9JDeGkdkfSOy1dmNaoK8kkF8GppAKYJLRoX_tI


###
POST http://localhost:3000/Databases
Content-Type: application/json

{
    "database_name": "Bocchi's DB",
    "database_owner": "Hitori Gotoh",
    "database_elements":[
        {
            "class_name": "Guitar",
            "attribute_list": [
                {"attribute":"body", "type":"String"},
                {"attribute":"neck", "type":"String"},
                {"attribute":"strings", "type":"Int"}
            ]
        },
        {
            "class_name": "Job",
            "attribute_list": [
                {"attribute":"position", "type":"String"},
                {"attribute":"pay", "type":"Float"}
            ]
        }
    ],
    "database_class_relationships": [] 
}


###
GET http://localhost:3000/Databases/database
Content-Type: application/json

{
    "database_id": "b65d592b-11f0-474b-9a75-2805a794619a"
}