// Retrieves all of the users in the database
GET http://localhost:3000/Users


###

// Creates a new user and adds it to the database
POST http://localhost:3000/Users
Content-Type: application/json 

{
    "email":"nijika@bocchi.jp",
    "password":"nijikadabest"
}

###

// Deletes a user given the email address (after the email/"EMAIL_HERE"
DELETE http://localhost:3000/Users/email/bocchi@bocchi.jp


###

// Queries ONE person given email and password as parameter
GET http://localhost:3000/Users
Content-Type: application/json

{
    "email":"nijika@bocchi.jp",
    "password":"nijikadabest"
}


###
POST http://localhost:3000/Users/login
Content-Type: application/json

{
    "email" : "bocchi@bocchi.jp",
    "password":"literallybocchi"
}


###
GET http://localhost:3000/Users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiYm9jY2hpQGJvY2NoaS5qcCIsImlhdCI6MTcwOTg0MjMzMH0.egdaa9JDeGkdkfSOy1dmNaoK8kkF8GppAKYJLRoX_tI


###
POST http://localhost:3000/Databases
Content-Type: application/json

{
    "database_name": "Bocchi's DB",
    "database_owner": "Hitori Gotoh",
    "data_variable_1": "Guitar",
    "data_variable_2": "Pink"
}